trigger:
- master

pool:
  name: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install --legacy-peer-deps
    npm run build
  displayName: 'npm install and build'
