trigger:
  branches:
    include:
      - main  # Or change to master/dev based on your branch

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Install and Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - script: |
        npm install --legacy-peer-deps
        npm run build
      displayName: 'Run npm install and build'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'build'  # Change this if your build output folder is different (e.g., dist)
        artifactName: 'drop'
      displayName: 'Publish Artifacts'

- stage: Deploy
  displayName: 'Deployment Stage'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: 'Deploy Job'
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
      displayName: 'Download Build Artifacts'

    - script: |
        echo "Deployment started..."
        echo "You can replace this with your actual deploy command (Azure CLI, FTP, etc)"
      displayName: 'Dummy Deploy Step'
